//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiziFilmSatis.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Filmdizi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Filmdizi()
        {
            this.Tbl_Hareket = new HashSet<Tbl_Hareket>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public Nullable<int> Katid { get; set; }
        public Nullable<int> Turid { get; set; }
        public Nullable<int> Yonetmenid { get; set; }
        public string Detay { get; set; }
        public string Foto { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string Video { get; set; }
    
        public virtual Tbl_Kategori Tbl_Kategori { get; set; }
        public virtual Tbl_Tur Tbl_Tur { get; set; }
        public virtual Tbl_Yonetmen Tbl_Yonetmen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Hareket> Tbl_Hareket { get; set; }
    }
}
